[mypy]
python_version = 3.11
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

[mypy-presidio_analyzer.*]
ignore_missing_imports = True

[mypy-presidio_anonymizer.*]
ignore_missing_imports = True

[mypy-spacy.*]
ignore_missing_imports = True

[mypy-faker.*]
ignore_missing_imports = True
